#!/bin/sh

# ./hello.tl
pushd hello || exit 1
hyperfine -N ./hello.mawk ./hello.lua ./hello-fnl.lua ./hello.gawk ./hello.bash ./hello.js ./hello.zsh  ./hello.ksh ./hello.pl ./hello.tcl ./hello.janet ./hello.py
popd
